/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model/0.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tmpj639y00eply.geometry}
        material={nodes.tmpj639y00eply.material}
      />
    </group>
  )
}

useGLTF.preload('/model/0.glb')
